[package]
name = "scripture-tui"
version = "0.1.0"
authors = ["Ephraim Kunz <ephraimkunz@me.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.27"
roxmltree = "0.19"
rusqlite = "0.30"
tui = { package = "ratatui", version = "0.25", features = ["unstable-rendered-line-info"]}
