[package]
name = "scripture-tui"
version = "0.1.0"
authors = ["Ephraim Kunz <ephraimkunz@me.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.28"
roxmltree = "0.20"
rusqlite = "0.32"
tui = { package = "ratatui", version = "0.28", features = ["unstable-rendered-line-info"]}
